---
title: "Gene Expression Analysis: GDS5205"
output: html_notebook
---

```{r}
# obtain publicly available dataset from Gene Expression Omnibus
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
 BiocManager::install("GEOquery")
library(GEOquery)
gds_data <- getGEO("GDS5205")

```
```{r}
#establish expression array from imported data
expression_matrix <- Table(gds_data)
```


```{r}
#establish group A and group B from metadata
#Group A includes 31 samples from intermediate survival group
group_A = c("GSM1299560","GSM1299559","GSM1299558","GSM1299557","GSM1299556","GSM1299555","GSM1299554","GSM1299553","GSM1299552","GSM1299551","GSM1299550","GSM1299549","GSM1299548","GSM1299547","GSM1299546","GSM1299545","GSM1299544","GSM1299543","GSM1299542","GSM1299541","GSM1299540","GSM1299539","GSM1299538","GSM1299577","GSM1299537","GSM1299536","GSM1299535","GSM1299534","GSM1299576","GSM1299533","GSM1299532")

```

```{r}
#Group B includes 23 samples from longtertm survival group
group_B = c("GSM1299586","GSM1299585","GSM1299574","GSM1299573","GSM1299572","GSM1299571","GSM1299584","GSM1299583","GSM1299570","GSM1299569","GSM1299568","GSM1299567","GSM1299566","GSM1299582","GSM1299565","GSM1299564","GSM1299581","GSM1299563","GSM1299562","GSM1299561","GSM1299580","GSM1299579","GSM1299578")

```

```{r}
#save gene and prove names
probe_names = expression_matrix$ID_REF
gene_names = expression_matrix$IDENTIFIER

```

```{r}
#clean and reformat data to only include our groups of interest
rownames(expression_matrix) = probe_names
columns_to_remove <- c("ID_REF", "IDENTIFIER")
expression_matrix <- expression_matrix[, !names(expression_matrix) %in% columns_to_remove]
samples_A_B = c(group_A, group_B)
cols_to_keep <- colnames(expression_matrix) %in% samples_A_B
dat <- expression_matrix[, cols_to_keep, ]
dat <- as.matrix(dat)

```

```{r}

# test for outliers
#Correlation Heat Map
dat.cor <- cor(dat)
 
layout(matrix(c(1,1,1,1,1,1,1,1,2,2), 5, 2, byrow = TRUE))
par(oma=c(5,7,1,1))
cx <- rev(colorpanel(25,"yellow","black","blue"))
leg <- seq(min(dat.cor,na.rm=T),max(dat.cor,na.rm=T),length=10)
image(dat.cor,main="Correlation plot of Data",axes=F,col=cx)
axis(1,at=seq(0,1,length=ncol(dat.cor)),label=dimnames(dat.cor)[[2]],cex.axis=0.9,las=2)
axis(2,at=seq(0,1,length=ncol(dat.cor)),label=dimnames(dat.cor)[[2]],cex.axis=0.9,las=2)

image(as.matrix(leg),col=cx,axes=F)
tmp <- round(leg,2)
axis(1,at=seq(0,1,length=length(leg)),labels=tmp,cex.axis=1)

```

```{r}
#2D PCA Plot
dat.loads <- dat.pca$x[,1:2]
plot(dat.loads[,1],dat.loads[,2],main="Sample PCA plot",xlab="p1",ylab="p2",col='red',cex=1,pch=15)
text(dat.loads,label=dimnames(dat)[[2]],pos=1,cex=0.5)

```

```{r}

# 2D sample pca plot
dat.pca <- prcomp(dat)
dat.loads <- dat.pca$x[,1:2]
plot(dat.loads[,1],dat.loads[,2],main="Sample PCA plot",xlab="p1",ylab="p2",col='red',cex=1,pch=15)
text(dat.loads,label=dimnames(dat)[[2]],pos=1,cex=0.5)
```

```{r}

#remove outliers
outliers <- c("GSM1299566", "GSM1299539", "GSM1299579")
    remove_vector <- unlist(outliers)

group_A <- group_A[!group_A %in% remove_vector]

group_B <- group_B[!group_B %in% remove_vector]
samples_A_B <- samples_A_B[!samples_A_B %in% remove_vector]
length(group_A)

length(group_B)

length(samples_A_B)

dat <- dat[, !colnames(dat) %in% outliers]
 
dim(dat)



```
```{r}
#check for missing data, but none found
sum(is.na(dat))

```


```{r}
# filter out genes that have low expression values by Coefficient of variation
gene_mean <- apply(dat, 1, mean, na.rm = TRUE)
gene_sd <- apply(dat, 1, sd, na.rm = TRUE)
gene_cv <- gene_sd / gene_mean
 
hist(log(gene_cv), main = "Distribution of log(CV) values", xlab = "log(CV)", col = "skyblue", breaks = 50)

cv_cutoff_percentile <- 0.05
cv_cutoff_value <- quantile(gene_cv, probs = cv_cutoff_percentile, na.rm = TRUE)
genes_to_keep <- names(gene_cv[gene_cv > cv_cutoff_value])
filtered_expression_data <- dat[genes_to_keep, ]

```
```{r}
# conduct some method of feature selection with appropriate statistical method (students t test, since two groups)

s1 <- which(colnames(filtered_expression_data) %in% group_A)
s2 <- which(colnames(filtered_expression_data) %in% group_B)

t.test.all.genes <- function(x,s1,s2) {
	x1 <- x[s1]
	x2 <- x[s2]
	x1 <- as.numeric(x1)
	x2 <- as.numeric(x2)
	t.out <- t.test(x1,x2, alternative="two.sided",var.equal=T)
	out <- as.numeric(t.out$p.value)
	return(out)
}

rawp <- apply(filtered_expression_data,1,t.test.all.genes,s1,s2)
```

```{r}
# Adjust for multiplicity, then provide the number of genes retained with the associated score (p-value, weight, test statistic, etc.) and threshold value that you used
#Note a very permissive p-value was selected as cutoff to facilitate the remainer of the assignment

library(multtest)
adjusted_results <- mt.rawp2adjp(rawp, proc=c("BH"))
adj_p_values_ordered <- adjusted_results$adjp[order(adjusted_results$index), "BH"]
significant_p_values <- adj_p_values_ordered[adj_p_values_ordered < 0.17]
print(paste("Number of significant p-values:", length(significant_p_values)))
```

```{r}
# Plot the scores of those genes retained in a histogram
hist(significant_p_values,
     main = "Histogram of Significant Adjusted P-values (< 0.17)",
     xlab = "Adjusted P-value",
     col = "lightblue",
     border = "black",
     breaks = seq(0, 0.2, by = 0.01) # Optional: set specific breaks
)
```
```{r}
#save only the most significant genes 
filter_gene_names = rownames(filtered_expression_data)

adjp_sorted <- adjusted_results$adjp
original_order_index <- adjusted_results$index

adjp_original_order <- adjp_sorted[order(original_order_index), ]

adjp_bh_original_order <- adjp_sorted[order(original_order_index), "BH"]

results_df <- data.frame(
  GeneName = filter_gene_names,
  RawPValue = rawp,
  AdjustedPValue_BH = adjp_bh_original_order
)

```

```{r}
#fnd and save the probes and genes of the relevant identified genes
df_sorted_asc <- results_df[order(results_df$AdjustedPValue_BH), ]
first_27_rows <- df_sorted_asc[1:27, ]
retained_probes = rownames(first_27_rows)
indices <- which(probe_names %in% retained_probes)
retained_genes <- gene_names[indices]
```

```{r}
# subset your data by the genes that you determined
subsetted_data <- filtered_expression_data[
  rownames(filtered_expression_data) %in% retained_probes,
  ]
```

```{r}
#use one of the clustering or dimensionality reduction methods discussed in class to visualize the samples in two-dimensional space (xy scatter plot, dendrogram, etc.

dat.pca <- prcomp(t(subsetted_data),cor=F)
ann.dat2 <-list()
for (item in samples_A_B) {
  if (item %in% group_A) {
    ann.dat2[[item]] <- 1
  } else if (item %in% group_B) {
    ann.dat2[[item]] <- 0
  } else {
    # Handle cases where an item might not belong to either group
    group_indicator_list[[item]] <- NA 
  }
}
ann.dat2
```
```{r}
dat.loadings <- dat.pca$x[,1:3]
par(mfrow=c(2,2))
plot(range(dat.loadings[,1]),range(dat.loadings[,2]),type="n",xlab='p1',ylab='p2',main='PCA plot\np2 vs. p1')
points(dat.loadings[,1][ann.dat2==1], dat.loadings[,2][ann.dat2==1],col=1,bg='red',pch=21,cex=1.5)
points(dat.loadings[,1][ann.dat2==0], dat.loadings[,2][ann.dat2==0],col=1,bg='blue',pch=21,cex=1.5)

plot(range(dat.loadings[,1]),range(dat.loadings[,3]),type="n",xlab='p1',ylab='p3',main='PCA plot\np3 vs. p1')
points(dat.loadings[,1][ann.dat2==1],dat.loadings[,3][ann.dat2==1],col=1,bg='red',pch=21,cex=1.5)
points(dat.loadings[,1][ann.dat2==0], dat.loadings[,3][ann.dat2==0],col=1,bg='blue',pch=21,cex=1.5)

plot(range(dat.loadings[,2]),range(dat.loadings[,3]),xlab='p2',type="n",ylab='p3',main='PCA plot\np3 vs. p2')
points(dat.loadings[,2][ann.dat2==1],dat.loadings[,3][ann.dat2==1],col=1,bg='red',pch=21,cex=1.5)
points(dat.loadings[,2][ann.dat2==0], dat.loadings[,3][ann.dat2==0],col=1,bg='blue',pch=21,cex=1.5)

```
```{r}
# Using these linear projections of the original data (i.e. cluster centroids, latent variables, etc.), use a classification method to classify the samples into their respective classes
library(factoextra)

data_numeric <- as.matrix(subsetted_data)
data_scaled <- scale(data_numeric)
k_clusters <- kmeans(data_scaled, centers = 3, nstart = 25)
fviz_cluster(k_clusters, 
             data = data_scaled,
             geom = "point",
             ellipse.type = "euclid", 
             pointsize = 1.5,
             palette = "jco",
             main = "K-means Cluster Plot (PCA reduced dimensions)",
             ggtheme = theme_minimal())
```
```{r}
# find the top 5 discriminant genes from your analysis  
class_a_cols <- 1:30
class_b_cols <- 31:51
groups <- factor(c(rep("GroupA", length(class_a_cols)), 
                   rep("GroupB", length(class_b_cols))))
expression_data <- subsetted_data[, c(class_a_cols, class_b_cols)]
expression_data <- subsetted_data[, c(class_a_cols, class_b_cols)]
design <- model.matrix(~0 + groups)
colnames(design) <- c("GroupA", "GroupB") # Rename columns for clarity
fit <- lmFit(expression_data, design)
contrast_matrix <- makeContrasts(GroupB - GroupA, levels = design)
fit_contrast <- contrasts.fit(fit, contrast_matrix)
fit_contrast <- eBayes(fit_contrast)
top_regulated <- topTable(fit_contrast, coef = 1, number = 5, adjust.method = "BH", sort.by = "logFC")
top_regulated
```


